### ISSUE TITLE
apparently everything is fine but doesnt insert any data on mysql

### ISSUE THREAD

**Issue by netoxss** [angely-dev/freeradius-api#10]

**Comment by netoxss** [comment]
Testing more times it works, for a user you need a ready group created

**Comment by angely-dev** [comment]
Please provide more info if you need help and not just "it doesn't work", at least how to reproduce the error.

> Testing more times it works, for a user you need a ready group created

It is not correct. You don't need a group to add a user. A user can be created without any group.

**Comment by netoxss** [comment]
> Please provide more info if you need help and not just "it doesn't work", at least how to reproduce the error.
> 
> > Testing more times it works, for a user you need a ready group created
> 
> It is not correct. You don't need a group to add a user. A user can be created without any group.

when i tryed to use the deafult template for create a user, the api returned code 409,  just worked when i first created the group that is on the create user json

**Comment by angely-dev** [comment]
Yes, the template you mention is just example data. You can omit the `group` attribute and your user will be created without group.
