### ISSUE TITLE
Can i access the API interface from another workstation?

### ISSUE THREAD

**Issue by netoxss** [angely-dev/freeradius-api#11]
i changed the API url parameters to my host Ip and the code runs okay, but cant access on browser

**Comment by netoxss** [comment]
Just run: uvicorn api:app --host 0.0.0.0 --port 8000

**Comment by angely-dev** [comment]
This project is a FastAPI app, you should look into: https://fastapi.tiangolo.com/deployment/

**Comment by netoxss** [comment]
> This project is a FastAPI app, you should look into: https://fastapi.tiangolo.com/deployment/

thxx
